---
- name: install java and net tools
  hosts: 65.2.143.99
  tasks:
    - name: Update repositories cache
      ansible.builtin.apt:
        update_cache: yes
        force_apt_get: true
        cache_valid_time : 3600

    - name: Install the package "java"
      ansible.builtin.apt:
        name: openjdk-8-jre-headless

    - name: Install the package "net-tools"
      ansible.builtin.apt:
        name: net-tools

- name: Download and unpack nexus installer
  hosts: 65.2.143.99
  tasks:
    - name: Download nexus
      ansible.builtin.get_url: 
        url: https://download.sonatype.com/nexus/3/nexus-3.88.0-08-linux-x86_64.tar.gz
        dest: /opt/
      register: nexus_file

    - name: Extract nexus-3.88.0-08-linux-x86_64.tar.gz into /opt/
      ansible.builtin.unarchive:
        src: "{{nexus_file.dest}}"
        dest: /opt/
        remote_src: yes

    - name: Find nexus Folder
      ansible.builtin.find:
        paths: /opt/
        patterns: "nexus-*"
        file_type: directory
      register: find_result

    - name : check nexus folder stats
      ansible.builtin.stat:
        path: /opt/nexus
      register: stat_result
    - debug: msg={{stat_result.stat.exists}}

    - name: Rename nexus folder
      ansible.builtin.shell: mv "{{find_result.files[0].path}}" /opt/nexus
      when: not stat_result.stat.exists


- name: create nexus user for nexus folders
  hosts: 65.2.143.99
  tasks:
    - name: Ensure group "nexus" exists
      ansible.builtin.group:
        name: nexus
        state: present

    - name: Add the user 'nexus' with a specific uid and a primary group of 'admin'
      ansible.builtin.user:
        name: nexus
        comment: nexus user
        group: nexus

    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: /opt/nexus
        state: directory
        owner: nexus
        group: nexus
        recurse: yes